import type { ServiceQuantity } from "./types";

export type BoostingPlatform =
  | "meta"
  | "telegram"
  | "tiktok"
  | "twitter-x"
  | "youtube"
  | "spotify"
  | "twitch";
export type BoostingNetwork =
  | "facebook"
  | "instagram"
  | "telegram"
  | "tiktok"
  | "twitter-x"
  | "youtube"
  | "spotify";

export const supportedServiceQuantities = [
  100, 500, 1000, 10000, 50000,
] as const satisfies readonly ServiceQuantity[];

export type BoostingCatalogRow = readonly [
  serviceId: number,
  platform: BoostingPlatform,
  network: BoostingNetwork | null,
  name: string,
  slug: string,
  category: string,
  pricePerThousand: string,
  minQuantity: number,
  maxQuantity: number,
  deliveryTime: string,
  iconUrl: string | null,
];

// Generated from the PH market CSV source. Re-run scripts/generate-boosting-catalog.mjs to refresh.
export const boostingCatalogRows = [
  [
    20062,
    "meta",
    "facebook",
    "Facebook Comments (Customized)",
    "facebook-comments-custom-no-refill",
    "facebook-boosting",
    "17.45",
    5,
    500000,
    "19 hours 8 minutes",
    "/logos/facebook.svg",
  ],
  [
    20059,
    "meta",
    "facebook",
    "Facebook Comments (Randomized)",
    "facebook-comments-random-no-refill",
    "facebook-boosting",
    "17.45",
    5,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21193,
    "meta",
    "facebook",
    "Facebook Followers (Lifetime)",
    "facebook-followers-global-lifetime",
    "facebook-boosting",
    "1.80",
    50,
    300000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21188,
    "meta",
    "facebook",
    "Facebook Followers",
    "facebook-followers-global-no-refill",
    "facebook-boosting",
    "1.47",
    50,
    300000,
    "15 hours 30 minutes",
    "/logos/facebook.svg",
  ],
  [
    21123,
    "meta",
    "facebook",
    "Facebook Followers (Premium, Lifetime)",
    "facebook-followers-high-quality-lifetime",
    "facebook-boosting",
    "2.19",
    10,
    100000,
    "3 hours 54 minutes",
    "/logos/facebook.svg",
  ],
  [
    21118,
    "meta",
    "facebook",
    "Facebook Followers (Premium)",
    "facebook-followers-high-quality-no-refill",
    "facebook-boosting",
    "1.58",
    10,
    500000,
    "23 hours 32 minutes",
    "/logos/facebook.svg",
  ],
  [
    20923,
    "meta",
    "facebook",
    "Facebook Followers (Standard, Lifetime)",
    "facebook-followers-low-quality-lifetime",
    "facebook-boosting",
    "37.80",
    100,
    5000,
    "59 minutes",
    "/logos/facebook.svg",
  ],
  [
    18791,
    "meta",
    "facebook",
    "Facebook Followers (Standard)",
    "facebook-followers-low-quality-no-refill",
    "facebook-boosting",
    "1.79",
    100,
    1000000,
    "4 hours 9 minutes",
    "/logos/facebook.svg",
  ],
  [
    20051,
    "meta",
    "facebook",
    "Facebook Group Members (Lifetime)",
    "facebook-group-members-lifetime",
    "facebook-boosting",
    "2.89",
    10,
    100000,
    "54 minutes",
    "/logos/facebook.svg",
  ],
  [
    20046,
    "meta",
    "facebook",
    "Facebook Group Members",
    "facebook-group-members-no-refill",
    "facebook-boosting",
    "2.33",
    10,
    100000,
    "53 minutes",
    "/logos/facebook.svg",
  ],
  [
    21051,
    "meta",
    "facebook",
    "Facebook Group Members (Premium, Lifetime)",
    "facebook-group-members-high-quality-lifetime",
    "facebook-boosting",
    "3.73",
    10,
    100000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21048,
    "meta",
    "facebook",
    "Facebook Group Members (Premium)",
    "facebook-group-members-high-quality-no-refill",
    "facebook-boosting",
    "2.73",
    10,
    100000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21497,
    "meta",
    "facebook",
    "Facebook Group Members (Standard, Lifetime)",
    "facebook-group-members-low-quality-lifetime",
    "facebook-boosting",
    "2.92",
    100,
    100000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21492,
    "meta",
    "facebook",
    "Facebook Group Members (Standard)",
    "facebook-group-members-low-quality-no-refill",
    "facebook-boosting",
    "2.15",
    100,
    100000,
    "9 hours 48 minutes",
    "/logos/facebook.svg",
  ],
  [
    18879,
    "meta",
    "facebook",
    "Facebook Likes",
    "facebook-likes",
    "facebook-boosting",
    "13.65",
    1000,
    100000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19911,
    "meta",
    "facebook",
    "Facebook Live Stream Views",
    "facebook-live-stream-views",
    "facebook-boosting",
    "4.00",
    10,
    500000,
    "20 minutes",
    "/logos/facebook.svg",
  ],
  [
    20054,
    "meta",
    "facebook",
    "Facebook Live Stream Views",
    "facebook-live-stream-views-no-refill",
    "facebook-boosting",
    "20.91",
    5,
    2000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19889,
    "meta",
    "facebook",
    "Facebook Live Stream Views (120 Min)",
    "facebook-live-stream-views-120-min",
    "facebook-boosting",
    "28.47",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19981,
    "meta",
    "facebook",
    "Facebook Live Stream Views (1440 Min)",
    "facebook-live-stream-views-1440-min",
    "facebook-boosting",
    "1334.57",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19885,
    "meta",
    "facebook",
    "Facebook Live Stream Views (15 Min)",
    "facebook-live-stream-views-15-min",
    "facebook-boosting",
    "3.56",
    10,
    50000,
    "34 minutes",
    "/logos/facebook.svg",
  ],
  [
    19900,
    "meta",
    "facebook",
    "Facebook Live Stream Views (150 Min)",
    "facebook-live-stream-views-150-min",
    "facebook-boosting",
    "37.13",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19890,
    "meta",
    "facebook",
    "Facebook Live Stream Views (180 Min)",
    "facebook-live-stream-views-180-min",
    "facebook-boosting",
    "35.59",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19860,
    "meta",
    "facebook",
    "Facebook Live Stream Views (20 Min)",
    "facebook-live-stream-views-20-min",
    "facebook-boosting",
    "4.80",
    50,
    5000,
    "32 minutes",
    "/logos/facebook.svg",
  ],
  [
    19902,
    "meta",
    "facebook",
    "Facebook Live Stream Views (210 Min)",
    "facebook-live-stream-views-210-min",
    "facebook-boosting",
    "51.98",
    10,
    500000,
    "3 hours 36 minutes",
    "/logos/facebook.svg",
  ],
  [
    19891,
    "meta",
    "facebook",
    "Facebook Live Stream Views (240 Min)",
    "facebook-live-stream-views-240-min",
    "facebook-boosting",
    "42.71",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19861,
    "meta",
    "facebook",
    "Facebook Live Stream Views (25 Min)",
    "facebook-live-stream-views-25-min",
    "facebook-boosting",
    "5.91",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19904,
    "meta",
    "facebook",
    "Facebook Live Stream Views (270 Min)",
    "facebook-live-stream-views-270-min",
    "facebook-boosting",
    "66.83",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19886,
    "meta",
    "facebook",
    "Facebook Live Stream Views (30 Min)",
    "facebook-live-stream-views-30-min",
    "facebook-boosting",
    "7.12",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19905,
    "meta",
    "facebook",
    "Facebook Live Stream Views (300 Min)",
    "facebook-live-stream-views-300-min",
    "facebook-boosting",
    "74.25",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19878,
    "meta",
    "facebook",
    "Facebook Live Stream Views (330 Min)",
    "facebook-live-stream-views-330-min",
    "facebook-boosting",
    "78.24",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19863,
    "meta",
    "facebook",
    "Facebook Live Stream Views (35 Min)",
    "facebook-live-stream-views-35-min",
    "facebook-boosting",
    "8.24",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19892,
    "meta",
    "facebook",
    "Facebook Live Stream Views (360 Min)",
    "facebook-live-stream-views-360-min",
    "facebook-boosting",
    "85.41",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19864,
    "meta",
    "facebook",
    "Facebook Live Stream Views (40 Min)",
    "facebook-live-stream-views-40-min",
    "facebook-boosting",
    "9.47",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19907,
    "meta",
    "facebook",
    "Facebook Live Stream Views (420 Min)",
    "facebook-live-stream-views-420-min",
    "facebook-boosting",
    "103.96",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19896,
    "meta",
    "facebook",
    "Facebook Live Stream Views (45 Min)",
    "facebook-live-stream-views-45-min",
    "facebook-boosting",
    "11.14",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19893,
    "meta",
    "facebook",
    "Facebook Live Stream Views (480 Min)",
    "facebook-live-stream-views-480-min",
    "facebook-boosting",
    "106.76",
    10,
    50000,
    "7 hours 18 minutes",
    "/logos/facebook.svg",
  ],
  [
    19866,
    "meta",
    "facebook",
    "Facebook Live Stream Views (50 Min)",
    "facebook-live-stream-views-50-min",
    "facebook-boosting",
    "11.81",
    50,
    5000,
    "1 hours 10 minutes",
    "/logos/facebook.svg",
  ],
  [
    19909,
    "meta",
    "facebook",
    "Facebook Live Stream Views (540 Min)",
    "facebook-live-stream-views-540-min",
    "facebook-boosting",
    "133.66",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19887,
    "meta",
    "facebook",
    "Facebook Live Stream Views (60 Min)",
    "facebook-live-stream-views-60-min",
    "facebook-boosting",
    "14.24",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19883,
    "meta",
    "facebook",
    "Facebook Live Stream Views (600 Min)",
    "facebook-live-stream-views-600-min",
    "facebook-boosting",
    "142.22",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19868,
    "meta",
    "facebook",
    "Facebook Live Stream Views (70 Min)",
    "facebook-live-stream-views-70-min",
    "facebook-boosting",
    "16.61",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19910,
    "meta",
    "facebook",
    "Facebook Live Stream Views (720 Min)",
    "facebook-live-stream-views-720-min",
    "facebook-boosting",
    "178.21",
    10,
    500000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19869,
    "meta",
    "facebook",
    "Facebook Live Stream Views (80 Min)",
    "facebook-live-stream-views-80-min",
    "facebook-boosting",
    "18.95",
    50,
    5000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19888,
    "meta",
    "facebook",
    "Facebook Live Stream Views (90 Min)",
    "facebook-live-stream-views-90-min",
    "facebook-boosting",
    "21.35",
    10,
    50000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    18780,
    "meta",
    "facebook",
    "Facebook Page Likes (Lifetime)",
    "facebook-page-likes-lifetime",
    "facebook-boosting",
    "3.47",
    10,
    1000000,
    "19 minutes",
    "/logos/facebook.svg",
  ],
  [
    18775,
    "meta",
    "facebook",
    "Facebook Page Likes",
    "facebook-page-likes-no-refill",
    "facebook-boosting",
    "2.88",
    10,
    1000000,
    "12 hours 21 minutes",
    "/logos/facebook.svg",
  ],
  [
    18836,
    "meta",
    "facebook",
    "Facebook Plays (Lifetime)",
    "facebook-plays-lifetime",
    "facebook-boosting",
    "0.70",
    100,
    1000000000,
    "41 minutes",
    "/logos/facebook.svg",
  ],
  [
    18835,
    "meta",
    "facebook",
    "Facebook Plays",
    "facebook-plays-no-refill",
    "facebook-boosting",
    "0.58",
    100,
    1000000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    18828,
    "meta",
    "facebook",
    "Facebook Plays (30-Day Guarantee)",
    "facebook-plays-refill-30d",
    "facebook-boosting",
    "0.16",
    100,
    1000000000,
    "30 hours 27 minutes",
    "/logos/facebook.svg",
  ],
  [
    21535,
    "meta",
    "facebook",
    "Facebook Post Likes",
    "facebook-post-likes-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21569,
    "meta",
    "facebook",
    "Facebook Post Likes (Standard)",
    "facebook-post-likes-low-quality-no-refill",
    "facebook-boosting",
    "0.76",
    10,
    1000000,
    "10 minutes",
    "/logos/facebook.svg",
  ],
  [
    21541,
    "meta",
    "facebook",
    "Facebook Post Reaction (Angry)",
    "facebook-post-reaction-angry-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21537,
    "meta",
    "facebook",
    "Facebook Post Reaction (Care)",
    "facebook-post-reaction-care-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21539,
    "meta",
    "facebook",
    "Facebook Post Reaction (Haha)",
    "facebook-post-reaction-haha-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21003,
    "meta",
    "facebook",
    "Facebook Post Reaction (Like)",
    "facebook-post-reaction-like-no-refill",
    "facebook-boosting",
    "0.87",
    10,
    1000000,
    "21 hours 20 minutes",
    "/logos/facebook.svg",
  ],
  [
    21536,
    "meta",
    "facebook",
    "Facebook Post Reaction (Love)",
    "facebook-post-reaction-love-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "36 minutes",
    "/logos/facebook.svg",
  ],
  [
    21540,
    "meta",
    "facebook",
    "Facebook Post Reaction (Sad)",
    "facebook-post-reaction-sad-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21538,
    "meta",
    "facebook",
    "Facebook Post Reaction (Wow)",
    "facebook-post-reaction-wow-no-refill",
    "facebook-boosting",
    "0.78",
    10,
    1000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    18854,
    "meta",
    "facebook",
    "Facebook Post Reaction - (Premium)",
    "facebook-post-reaction-global-high-quality",
    "facebook-boosting",
    "4.21",
    50,
    100000,
    "18 minutes",
    "/logos/facebook.svg",
  ],
  [
    18899,
    "meta",
    "facebook",
    "Facebook Shares",
    "facebook-shares",
    "facebook-boosting",
    "6.83",
    1000,
    100000000,
    "12 hours 50 minutes",
    "/logos/facebook.svg",
  ],
  [
    21385,
    "meta",
    "facebook",
    "Facebook Shares (Lifetime)",
    "facebook-shares-lifetime",
    "facebook-boosting",
    "0.15",
    100,
    2147483647,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21383,
    "meta",
    "facebook",
    "Facebook Shares",
    "facebook-shares-no-refill",
    "facebook-boosting",
    "0.13",
    100,
    2147483647,
    "52 minutes",
    "/logos/facebook.svg",
  ],
  [
    21355,
    "meta",
    "facebook",
    "Facebook Shares (30-Day Guarantee)",
    "facebook-shares-refill-30d",
    "facebook-boosting",
    "0.12",
    100,
    2147483647,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    18889,
    "meta",
    "facebook",
    "Facebook Views",
    "facebook-views",
    "facebook-boosting",
    "0.68",
    1000,
    100000000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    99901,
    "meta",
    "facebook",
    "Facebook Followers (Hidden Data)",
    "facebook-followers-hidden-data",
    "facebook-boosting",
    "2.26",
    100,
    100000,
    "24–48 hours",
    "/logos/facebook.svg",
  ],
  [
    18837,
    "meta",
    "facebook",
    "Facebook Views (30-Day Guarantee)",
    "facebook-views-refill-30d",
    "facebook-boosting",
    "0.23",
    50,
    2000000000,
    "1 hours 27 minutes",
    "/logos/facebook.svg",
  ],
  [
    18838,
    "meta",
    "facebook",
    "Facebook Views (60-Day Guarantee)",
    "facebook-views-refill-60d",
    "facebook-boosting",
    "0.22",
    100,
    2147483647,
    "2 hours 59 minutes",
    "/logos/facebook.svg",
  ],
  [
    21422,
    "meta",
    "facebook",
    "Facebook Watch Time (1h Video, Ultra Fast, Lifetime)",
    "facebook-watch-time-1h-video-ultra-fast-lifetime",
    "facebook-boosting",
    "27.04",
    1000,
    1000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21421,
    "meta",
    "facebook",
    "Facebook Watch Time (2h Video, Ultra Fast, Lifetime)",
    "facebook-watch-time-2h-video-ultra-fast-lifetime",
    "facebook-boosting",
    "19.84",
    1000,
    1000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    21420,
    "meta",
    "facebook",
    "Facebook Watch Time (3h Video, Ultra Fast, Lifetime)",
    "facebook-watch-time-3h-video-ultra-fast-lifetime",
    "facebook-boosting",
    "18.07",
    1000,
    1000,
    "New Service",
    "/logos/facebook.svg",
  ],
  [
    19477,
    "meta",
    "instagram",
    "Instagram Comments (Customized)",
    "instagram-comments-custom-no-refill",
    "instagram-boosting",
    "5.66",
    10,
    10000,
    "8 hours 4 minutes",
    "/logos/instagram.svg",
  ],
  [
    19481,
    "meta",
    "instagram",
    "Instagram Comments (Randomized, Lifetime)",
    "instagram-comments-random-lifetime",
    "instagram-boosting",
    "11.69",
    50,
    20000,
    "5 hours 46 minutes",
    "/logos/instagram.svg",
  ],
  [
    21017,
    "meta",
    "instagram",
    "Instagram Comments (Randomized)",
    "instagram-comments-random-no-refill",
    "instagram-boosting",
    "1.84",
    10,
    100000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    20117,
    "meta",
    "instagram",
    "Instagram Followers (Lifetime)",
    "instagram-followers-lifetime",
    "instagram-boosting",
    "7.66",
    10,
    5000000,
    "11 minutes",
    "/logos/instagram.svg",
  ],
  [
    19457,
    "meta",
    "instagram",
    "Instagram Followers",
    "instagram-followers-no-refill",
    "instagram-boosting",
    "3.13",
    100,
    100000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    21318,
    "meta",
    "instagram",
    "Instagram Followers (Aged Accounts) (AI Sustained)",
    "instagram-followers-old-accounts-ai-refill",
    "instagram-boosting",
    "4.31",
    50,
    1000000,
    "2 hours 50 minutes",
    "/logos/instagram.svg",
  ],
  [
    21534,
    "meta",
    "instagram",
    "Instagram Followers (Aged Accounts, Lifetime)",
    "instagram-followers-old-accounts-lifetime",
    "instagram-boosting",
    "3.94",
    10,
    100000,
    "3 hours 8 minutes",
    "/logos/instagram.svg",
  ],
  [
    21503,
    "meta",
    "instagram",
    "Instagram Followers (Active Aged Accounts, Lifetime)",
    "instagram-followers-old-accts-w-posts-lifetime",
    "instagram-boosting",
    "4.37",
    10,
    100000,
    "55 minutes",
    "/logos/instagram.svg",
  ],
  [
    21498,
    "meta",
    "instagram",
    "Instagram Followers (Active Aged Accounts)",
    "instagram-followers-old-accts-w-posts-no-refill",
    "instagram-boosting",
    "2.72",
    10,
    100000,
    "10 hours 42 minutes",
    "/logos/instagram.svg",
  ],
  [
    20985,
    "meta",
    "instagram",
    "Instagram Followers (Organic)",
    "instagram-followers-real-accounts",
    "instagram-boosting",
    "3.44",
    10,
    100000,
    "7 hours 7 minutes",
    "/logos/instagram.svg",
  ],
  [
    20988,
    "meta",
    "instagram",
    "Instagram Followers (Organic, Lifetime)",
    "instagram-followers-real-accounts-lifetime",
    "instagram-boosting",
    "3.44",
    10,
    100000,
    "2 hours 11 minutes",
    "/logos/instagram.svg",
  ],
  [
    20617,
    "meta",
    "instagram",
    "Instagram Likes (Lifetime)",
    "instagram-likes-lifetime",
    "instagram-boosting",
    "0.93",
    10,
    10000000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    20893,
    "meta",
    "instagram",
    "Instagram Likes",
    "instagram-likes-no-refill",
    "instagram-boosting",
    "0.91",
    50,
    50000,
    "4 hours 42 minutes",
    "/logos/instagram.svg",
  ],
  [
    19501,
    "meta",
    "instagram",
    "Instagram Likes (Premium)",
    "instagram-likes-high-quality-no-refill",
    "instagram-boosting",
    "1.70",
    50,
    200000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    21047,
    "meta",
    "instagram",
    "Instagram Likes (Active Aged Accounts, Lifetime)",
    "instagram-likes-old-accts-w-posts-lifetime",
    "instagram-boosting",
    "0.88",
    10,
    1000000,
    "1 hours 10 minutes",
    "/logos/instagram.svg",
  ],
  [
    21042,
    "meta",
    "instagram",
    "Instagram Likes (Active Aged Accounts)",
    "instagram-likes-old-accts-w-posts-no-refill",
    "instagram-boosting",
    "0.82",
    10,
    1000000,
    "1 hours 27 minutes",
    "/logos/instagram.svg",
  ],
  [
    20084,
    "meta",
    "instagram",
    "Instagram Likes (Organic)",
    "instagram-likes-real-accounts-no-refill",
    "instagram-boosting",
    "1.15",
    50,
    1000000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    21032,
    "meta",
    "instagram",
    "Instagram Likes (Organic, Lifetime)",
    "instagram-likes-real-lifetime",
    "instagram-boosting",
    "0.82",
    100,
    1000000,
    "43 minutes",
    "/logos/instagram.svg",
  ],
  [
    19487,
    "meta",
    "instagram",
    "Instagram Shares",
    "instagram-shares-no-refill",
    "instagram-boosting",
    "0.77",
    100,
    500000,
    "10 hours 42 minutes",
    "/logos/instagram.svg",
  ],
  [
    19472,
    "meta",
    "instagram",
    "Instagram Video Views",
    "instagram-video-views-no-refill",
    "instagram-boosting",
    "0.01",
    50,
    50000000,
    "15 hours 40 minutes",
    "/logos/instagram.svg",
  ],
  [
    19548,
    "meta",
    "instagram",
    "Instagram Views",
    "instagram-views",
    "instagram-boosting",
    "1.51",
    1000,
    1000000,
    "New Service",
    "/logos/instagram.svg",
  ],
  [
    19468,
    "meta",
    "instagram",
    "Instagram Views",
    "instagram-views-no-refill",
    "instagram-boosting",
    "0.01",
    10,
    2147483647,
    "27 hours",
    "/logos/instagram.svg",
  ],
  [
    20399,
    "telegram",
    "telegram",
    "Telegram Comments (Randomized)",
    "telegram-comments-random",
    "telegram-boosting",
    "16.39",
    100,
    15000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20834,
    "telegram",
    "telegram",
    "Telegram Members",
    "telegram-members",
    "telegram-boosting",
    "9.30",
    100,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20937,
    "telegram",
    "telegram",
    "Telegram Members (Lifetime)",
    "telegram-members-lifetime",
    "telegram-boosting",
    "5.23",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20281,
    "telegram",
    "telegram",
    "Telegram Members",
    "telegram-members-no-refill",
    "telegram-boosting",
    "0.08",
    5,
    1000000,
    "59 hours 56 minutes",
    "/logos/telegram.svg",
  ],
  [
    20589,
    "telegram",
    "telegram",
    "Telegram Members (10-Day Guarantee)",
    "telegram-members-refill-10d",
    "telegram-boosting",
    "17.68",
    50,
    70000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20275,
    "telegram",
    "telegram",
    "Telegram Members (12-Day Guarantee)",
    "telegram-members-refill-12d",
    "telegram-boosting",
    "109.44",
    10,
    20000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20300,
    "telegram",
    "telegram",
    "Telegram Members (15-Day Guarantee)",
    "telegram-members-refill-15d",
    "telegram-boosting",
    "7.87",
    100,
    50000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20292,
    "telegram",
    "telegram",
    "Telegram Members (180-Day Guarantee)",
    "telegram-members-refill-180d",
    "telegram-boosting",
    "4.97",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20301,
    "telegram",
    "telegram",
    "Telegram Members (20-Day Guarantee)",
    "telegram-members-refill-20d",
    "telegram-boosting",
    "7.14",
    100,
    20000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20266,
    "telegram",
    "telegram",
    "Telegram Members (25-Day Guarantee)",
    "telegram-members-refill-25d",
    "telegram-boosting",
    "94.82",
    10,
    20000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20285,
    "telegram",
    "telegram",
    "Telegram Members (30-Day Guarantee)",
    "telegram-members-refill-30d",
    "telegram-boosting",
    "0.31",
    10,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20252,
    "telegram",
    "telegram",
    "Telegram Members (360-Day Guarantee)",
    "telegram-members-refill-360d",
    "telegram-boosting",
    "6.43",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20936,
    "telegram",
    "telegram",
    "Telegram Members (365-Day Guarantee)",
    "telegram-members-refill-365d",
    "telegram-boosting",
    "4.65",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20283,
    "telegram",
    "telegram",
    "Telegram Members (3-Day Guarantee)",
    "telegram-members-refill-3d",
    "telegram-boosting",
    "0.25",
    10,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20272,
    "telegram",
    "telegram",
    "Telegram Members (5-Day Guarantee)",
    "telegram-members-refill-5d",
    "telegram-boosting",
    "426.23",
    10,
    20000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20286,
    "telegram",
    "telegram",
    "Telegram Members (60-Day Guarantee)",
    "telegram-members-refill-60d",
    "telegram-boosting",
    "0.41",
    10,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20284,
    "telegram",
    "telegram",
    "Telegram Members (7-Day Guarantee)",
    "telegram-members-refill-7d",
    "telegram-boosting",
    "0.28",
    10,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20935,
    "telegram",
    "telegram",
    "Telegram Members (90-Day Guarantee)",
    "telegram-members-refill-90d",
    "telegram-boosting",
    "4.07",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20512,
    "telegram",
    "telegram",
    "Telegram Post Reaction",
    "telegram-post-reaction",
    "telegram-boosting",
    "0.10",
    10,
    200000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20367,
    "telegram",
    "telegram",
    "Telegram Post Reaction (Angry)",
    "telegram-post-reaction-angry",
    "telegram-boosting",
    "0.14",
    10,
    100000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20328,
    "telegram",
    "telegram",
    "Telegram Post Reaction (Like)",
    "telegram-post-reaction-like",
    "telegram-boosting",
    "0.14",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20332,
    "telegram",
    "telegram",
    "Telegram Post Reaction (Love)",
    "telegram-post-reaction-love",
    "telegram-boosting",
    "0.14",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20371,
    "telegram",
    "telegram",
    "Telegram Post Reaction (Automated)",
    "telegram-post-reaction-bot",
    "telegram-boosting",
    "0.14",
    10,
    1000000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20592,
    "telegram",
    "telegram",
    "Telegram Subscribers (Automated)",
    "telegram-subscribers-bot",
    "telegram-boosting",
    "10.70",
    100,
    300000,
    "New Service",
    "/logos/telegram.svg",
  ],
  [
    20317,
    "telegram",
    "telegram",
    "Telegram Views",
    "telegram-views",
    "telegram-boosting",
    "0.03",
    10,
    50000000,
    "6 minutes",
    "/logos/telegram.svg",
  ],
  [
    18746,
    "tiktok",
    "tiktok",
    "TikTok Comments (Customized)",
    "tiktok-comments-custom-no-refill",
    "tiktok-boosting",
    "9.58",
    1,
    100000,
    "24 hours 51 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18744,
    "tiktok",
    "tiktok",
    "TikTok Comments (Customized, Organic)",
    "tiktok-comments-custom-real-no-refill",
    "tiktok-boosting",
    "9.58",
    1,
    100000,
    "31 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18741,
    "tiktok",
    "tiktok",
    "TikTok Comments (Randomized, Organic)",
    "tiktok-comments-random-real-no-refill",
    "tiktok-boosting",
    "9.58",
    1,
    100000,
    "13 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21009,
    "tiktok",
    "tiktok",
    "TikTok Followers",
    "tiktok-followers-no-refill",
    "tiktok-boosting",
    "7.00",
    100,
    1000000,
    "71 hours 32 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21423,
    "tiktok",
    "tiktok",
    "TikTok Followers (Premium)",
    "tiktok-followers-high-quality-no-refill",
    "tiktok-boosting",
    "13.96",
    20,
    30000,
    "1 hours",
    "/logos/tiktok.svg",
  ],
  [
    21424,
    "tiktok",
    "tiktok",
    "TikTok Followers (Premium, 7-Day Guarantee)",
    "tiktok-followers-high-quality-refill-7d",
    "tiktok-boosting",
    "15.17",
    20,
    30000,
    "2 hours 4 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21036,
    "tiktok",
    "tiktok",
    "TikTok Followers (Organic)",
    "tiktok-followers-real",
    "tiktok-boosting",
    "18.98",
    10,
    100000,
    "125 hours",
    "/logos/tiktok.svg",
  ],
  [
    21041,
    "tiktok",
    "tiktok",
    "TikTok Followers (Organic, Lifetime)",
    "tiktok-followers-real-lifetime",
    "tiktok-boosting",
    "28.47",
    10,
    100000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    20906,
    "tiktok",
    "tiktok",
    "TikTok Followers (Organic)",
    "tiktok-followers-real-no-refill",
    "tiktok-boosting",
    "7.35",
    10,
    1000000,
    "26 hours 30 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18718,
    "tiktok",
    "tiktok",
    "TikTok Likes (Lifetime)",
    "tiktok-likes-lifetime",
    "tiktok-boosting",
    "0.20",
    10,
    1000000,
    "1 hours 9 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18713,
    "tiktok",
    "tiktok",
    "TikTok Likes",
    "tiktok-likes-no-refill",
    "tiktok-boosting",
    "0.14",
    10,
    1000000,
    "31 hours 26 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21609,
    "tiktok",
    "tiktok",
    "TikTok Likes (Premium, Lifetime)",
    "tiktok-likes-high-quality-lifetime",
    "tiktok-boosting",
    "0.30",
    10,
    100000,
    "1 hours 48 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21604,
    "tiktok",
    "tiktok",
    "TikTok Likes (Premium)",
    "tiktok-likes-high-quality-no-refill",
    "tiktok-boosting",
    "0.25",
    10,
    100000,
    "4 hours 45 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21525,
    "tiktok",
    "tiktok",
    "TikTok Likes (Organic)",
    "tiktok-likes-real-accounts-no-refill",
    "tiktok-boosting",
    "1.23",
    10,
    1000000,
    "5 hours 12 minutes",
    "/logos/tiktok.svg",
  ],
  [
    20111,
    "tiktok",
    "tiktok",
    "TikTok Likes (Organic, Lifetime)",
    "tiktok-likes-real-lifetime",
    "tiktok-boosting",
    "0.90",
    10,
    3000000,
    "1 hours 27 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21527,
    "tiktok",
    "tiktok",
    "TikTok Likes + Views (Organic)",
    "tiktok-likes-views-real-accounts-no-refill",
    "tiktok-boosting",
    "2.08",
    10,
    1000000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    18754,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views",
    "tiktok-live-stream-views",
    "tiktok-boosting",
    "1.56",
    10,
    2147483647,
    "9 minutes",
    "/logos/tiktok.svg",
  ],
  [
    20791,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (Lifetime)",
    "tiktok-live-stream-views-lifetime",
    "tiktok-boosting",
    "11.38",
    1,
    5000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    20759,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views",
    "tiktok-live-stream-views-no-refill",
    "tiktok-boosting",
    "0.04",
    10,
    2147483647,
    "3 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21485,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1020 Min)",
    "tiktok-live-stream-views-1020-min",
    "tiktok-boosting",
    "1986.85",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21486,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1050 Min)",
    "tiktok-live-stream-views-1050-min",
    "tiktok-boosting",
    "2045.29",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21487,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1080 Min)",
    "tiktok-live-stream-views-1080-min",
    "tiktok-boosting",
    "2103.72",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21488,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1110 Min)",
    "tiktok-live-stream-views-1110-min",
    "tiktok-boosting",
    "2162.16",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21489,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1140 Min)",
    "tiktok-live-stream-views-1140-min",
    "tiktok-boosting",
    "2220.60",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21490,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1170 Min)",
    "tiktok-live-stream-views-1170-min",
    "tiktok-boosting",
    "2279.03",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21310,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (120 Min)",
    "tiktok-live-stream-views-120-min",
    "tiktok-boosting",
    "26.89",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21491,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (1200 Min)",
    "tiktok-live-stream-views-1200-min",
    "tiktok-boosting",
    "2337.47",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21306,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (15 Min)",
    "tiktok-live-stream-views-15-min",
    "tiktok-boosting",
    "3.36",
    50,
    500000,
    "33 minutes",
    "/logos/tiktok.svg",
  ],
  [
    20739,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (150 Min)",
    "tiktok-live-stream-views-150-min",
    "tiktok-boosting",
    "103.30",
    50,
    100000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21311,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (180 Min)",
    "tiktok-live-stream-views-180-min",
    "tiktok-boosting",
    "40.33",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    20741,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (210 Min)",
    "tiktok-live-stream-views-210-min",
    "tiktok-boosting",
    "144.62",
    50,
    100000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21312,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (240 Min)",
    "tiktok-live-stream-views-240-min",
    "tiktok-boosting",
    "53.77",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    20743,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (270 Min)",
    "tiktok-live-stream-views-270-min",
    "tiktok-boosting",
    "185.94",
    50,
    100000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21307,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (30 Min)",
    "tiktok-live-stream-views-30-min",
    "tiktok-boosting",
    "6.72",
    50,
    500000,
    "32 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21313,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (300 Min)",
    "tiktok-live-stream-views-300-min",
    "tiktok-boosting",
    "80.66",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21462,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (330 Min)",
    "tiktok-live-stream-views-330-min",
    "tiktok-boosting",
    "642.80",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21314,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (360 Min)",
    "tiktok-live-stream-views-360-min",
    "tiktok-boosting",
    "87.38",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21464,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (390 Min)",
    "tiktok-live-stream-views-390-min",
    "tiktok-boosting",
    "759.68",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21465,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (420 Min)",
    "tiktok-live-stream-views-420-min",
    "tiktok-boosting",
    "818.11",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21466,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (450 Min)",
    "tiktok-live-stream-views-450-min",
    "tiktok-boosting",
    "876.55",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21467,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (480 Min)",
    "tiktok-live-stream-views-480-min",
    "tiktok-boosting",
    "934.99",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    20787,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (5 Min)",
    "tiktok-live-stream-views-5-min",
    "tiktok-boosting",
    "0.29",
    10,
    2147483647,
    "5 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21468,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (510 Min)",
    "tiktok-live-stream-views-510-min",
    "tiktok-boosting",
    "993.42",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21469,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (540 Min)",
    "tiktok-live-stream-views-540-min",
    "tiktok-boosting",
    "1051.86",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21470,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (570 Min)",
    "tiktok-live-stream-views-570-min",
    "tiktok-boosting",
    "1110.30",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21308,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (60 Min)",
    "tiktok-live-stream-views-60-min",
    "tiktok-boosting",
    "13.44",
    50,
    500000,
    "1 hours 48 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21471,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (600 Min)",
    "tiktok-live-stream-views-600-min",
    "tiktok-boosting",
    "1168.74",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21472,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (630 Min)",
    "tiktok-live-stream-views-630-min",
    "tiktok-boosting",
    "1227.17",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21473,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (660 Min)",
    "tiktok-live-stream-views-660-min",
    "tiktok-boosting",
    "1285.61",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21474,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (690 Min)",
    "tiktok-live-stream-views-690-min",
    "tiktok-boosting",
    "1344.04",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21475,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (720 Min)",
    "tiktok-live-stream-views-720-min",
    "tiktok-boosting",
    "1402.48",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21476,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (750 Min)",
    "tiktok-live-stream-views-750-min",
    "tiktok-boosting",
    "1460.92",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21477,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (780 Min)",
    "tiktok-live-stream-views-780-min",
    "tiktok-boosting",
    "1519.36",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21478,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (810 Min)",
    "tiktok-live-stream-views-810-min",
    "tiktok-boosting",
    "1577.79",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21479,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (840 Min)",
    "tiktok-live-stream-views-840-min",
    "tiktok-boosting",
    "1636.23",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21480,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (870 Min)",
    "tiktok-live-stream-views-870-min",
    "tiktok-boosting",
    "1694.67",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21309,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (90 Min)",
    "tiktok-live-stream-views-90-min",
    "tiktok-boosting",
    "20.17",
    50,
    500000,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21481,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (900 Min)",
    "tiktok-live-stream-views-900-min",
    "tiktok-boosting",
    "1753.10",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21482,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (930 Min)",
    "tiktok-live-stream-views-930-min",
    "tiktok-boosting",
    "1811.54",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21483,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (960 Min)",
    "tiktok-live-stream-views-960-min",
    "tiktok-boosting",
    "1869.98",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    21484,
    "tiktok",
    "tiktok",
    "TikTok Live Stream Views (990 Min)",
    "tiktok-live-stream-views-990-min",
    "tiktok-boosting",
    "1928.41",
    50,
    300,
    "New Service",
    "/logos/tiktok.svg",
  ],
  [
    18737,
    "tiktok",
    "tiktok",
    "TikTok Shares (Lifetime)",
    "tiktok-shares-lifetime",
    "tiktok-boosting",
    "0.16",
    10,
    2147483647,
    "4 hours 43 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18736,
    "tiktok",
    "tiktok",
    "TikTok Shares",
    "tiktok-shares-no-refill",
    "tiktok-boosting",
    "0.14",
    10,
    2147483647,
    "3 hours 23 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21621,
    "tiktok",
    "tiktok",
    "TikTok Video Views (Lifetime)",
    "tiktok-video-views-lifetime",
    "tiktok-boosting",
    "0.08",
    100,
    2147483647,
    "12 minutes",
    "/logos/tiktok.svg",
  ],
  [
    21356,
    "tiktok",
    "tiktok",
    "TikTok Video Views (Premium)",
    "tiktok-video-views-high-quality",
    "tiktok-boosting",
    "0.03",
    10,
    2147483647,
    "24 hours 12 minutes",
    "/logos/tiktok.svg",
  ],
  [
    18661,
    "twitter-x",
    "twitter-x",
    "Twitter/X Comments (Customized)",
    "twitter-x-comments-custom-no-refill",
    "twitter-x-boosting",
    "668.81",
    10,
    250,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18660,
    "twitter-x",
    "twitter-x",
    "Twitter/X Comments (Randomized)",
    "twitter-x-comments-random-no-refill",
    "twitter-x-boosting",
    "501.61",
    10,
    250,
    "New Service",
    "/logos/x.svg",
  ],
  [
    20815,
    "twitter-x",
    "twitter-x",
    "Twitter/X Followers",
    "twitter-x-followers-no-refill",
    "twitter-x-boosting",
    "10.08",
    10,
    50000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    20816,
    "twitter-x",
    "twitter-x",
    "Twitter/X Followers (30-Day Guarantee)",
    "twitter-x-followers-refill-30d",
    "twitter-x-boosting",
    "59.31",
    10,
    50000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    20817,
    "twitter-x",
    "twitter-x",
    "Twitter/X Followers (60-Day Guarantee)",
    "twitter-x-followers-refill-60d",
    "twitter-x-boosting",
    "94.90",
    10,
    50000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    20818,
    "twitter-x",
    "twitter-x",
    "Twitter/X Followers (90-Day Guarantee)",
    "twitter-x-followers-refill-90d",
    "twitter-x-boosting",
    "142.35",
    10,
    50000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18639,
    "twitter-x",
    "twitter-x",
    "Twitter/X Likes",
    "twitter-x-likes-no-refill",
    "twitter-x-boosting",
    "4.10",
    10,
    100000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18644,
    "twitter-x",
    "twitter-x",
    "Twitter/X Likes (30-Day Guarantee)",
    "twitter-x-likes-refill-30d",
    "twitter-x-boosting",
    "384.45",
    50,
    5000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18641,
    "twitter-x",
    "twitter-x",
    "Twitter/X Likes (Premium, 30-Day Guarantee)",
    "twitter-x-likes-high-quality-refill-30d",
    "twitter-x-boosting",
    "59.17",
    10,
    10000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18643,
    "twitter-x",
    "twitter-x",
    "Twitter/X Likes (Organic, 30-Day Guarantee)",
    "twitter-x-likes-real-refill-30d",
    "twitter-x-boosting",
    "42.04",
    10,
    10000,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18667,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (Lifetime)",
    "twitter-x-views-lifetime",
    "twitter-x-boosting",
    "0.05",
    100,
    2147483647,
    "New Service",
    "/logos/x.svg",
  ],
  [
    21027,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views",
    "twitter-x-views-no-refill",
    "twitter-x-boosting",
    "0.03",
    100,
    2147483647,
    "New Service",
    "/logos/x.svg",
  ],
  [
    21028,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (30-Day Guarantee)",
    "twitter-x-views-refill-30d",
    "twitter-x-boosting",
    "0.04",
    100,
    2147483647,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18671,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (Premium, Lifetime)",
    "twitter-x-views-high-quality-lifetime",
    "twitter-x-boosting",
    "0.05",
    100,
    217545811,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18668,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (Premium)",
    "twitter-x-views-high-quality-no-refill",
    "twitter-x-boosting",
    "0.05",
    100,
    217545811,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18669,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (Premium, 30-Day Guarantee)",
    "twitter-x-views-high-quality-refill-30d",
    "twitter-x-boosting",
    "0.05",
    100,
    217545811,
    "New Service",
    "/logos/x.svg",
  ],
  [
    18670,
    "twitter-x",
    "twitter-x",
    "Twitter/X Views (Premium, 365-Day Guarantee)",
    "twitter-x-views-high-quality-refill-365d",
    "twitter-x-boosting",
    "0.05",
    100,
    217545811,
    "New Service",
    "/logos/x.svg",
  ],
  [
    19609,
    "youtube",
    "youtube",
    "YouTube Comments (Customized)",
    "youtube-comments-custom-no-refill",
    "youtube-boosting",
    "6.98",
    5,
    5000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19666,
    "youtube",
    "youtube",
    "YouTube Comments (Randomized, Organic, Lifetime)",
    "youtube-comments-random-real-lifetime",
    "youtube-boosting",
    "71.18",
    5,
    10000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19664,
    "youtube",
    "youtube",
    "YouTube Comments (Randomized, Organic, 30-Day Guarantee)",
    "youtube-comments-random-real-refill-30d",
    "youtube-boosting",
    "59.31",
    5,
    10000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19665,
    "youtube",
    "youtube",
    "YouTube Comments (Randomized, Organic, 365-Day Guarantee)",
    "youtube-comments-random-real-refill-365d",
    "youtube-boosting",
    "65.24",
    5,
    10000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19715,
    "youtube",
    "youtube",
    "YouTube Likes",
    "youtube-likes",
    "youtube-boosting",
    "13.65",
    1000,
    100000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19604,
    "youtube",
    "youtube",
    "YouTube Likes (Lifetime)",
    "youtube-likes-lifetime",
    "youtube-boosting",
    "5.65",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19602,
    "youtube",
    "youtube",
    "YouTube Likes (30-Day Guarantee)",
    "youtube-likes-refill-30d",
    "youtube-boosting",
    "4.62",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19603,
    "youtube",
    "youtube",
    "YouTube Likes (365-Day Guarantee)",
    "youtube-likes-refill-365d",
    "youtube-boosting",
    "5.13",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19696,
    "youtube",
    "youtube",
    "YouTube Live Stream Views",
    "youtube-live-stream-views",
    "youtube-boosting",
    "19.57",
    5,
    100000,
    "10 minutes",
    "/logos/youtube.svg",
  ],
  [
    21375,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (120 Min)",
    "youtube-live-stream-views-120-min",
    "youtube-boosting",
    "3.22",
    50,
    10000000,
    "15 minutes",
    "/logos/youtube.svg",
  ],
  [
    21379,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (12h)",
    "youtube-live-stream-views-12h",
    "youtube-boosting",
    "18.99",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19712,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (1440 Min)",
    "youtube-live-stream-views-1440-min",
    "youtube-boosting",
    "38.19",
    50,
    5000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21371,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (15 Min)",
    "youtube-live-stream-views-15-min",
    "youtube-boosting",
    "0.39",
    50,
    10000000,
    "17 minutes",
    "/logos/youtube.svg",
  ],
  [
    21376,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (180 Min)",
    "youtube-live-stream-views-180-min",
    "youtube-boosting",
    "4.83",
    50,
    10000000,
    "10 minutes",
    "/logos/youtube.svg",
  ],
  [
    21380,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (24h)",
    "youtube-live-stream-views-24h",
    "youtube-boosting",
    "36.60",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19714,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (30 Day)",
    "youtube-live-stream-views-30-day",
    "youtube-boosting",
    "1145.65",
    50,
    5000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21372,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (30 Min)",
    "youtube-live-stream-views-30-min",
    "youtube-boosting",
    "0.78",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21377,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (360 Min)",
    "youtube-live-stream-views-360-min",
    "youtube-boosting",
    "6.33",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19598,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (3h)",
    "youtube-live-stream-views-3h",
    "youtube-boosting",
    "8.46",
    50,
    500000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19705,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (60 Min)",
    "youtube-live-stream-views-60-min",
    "youtube-boosting",
    "1.59",
    50,
    5000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21378,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (6h)",
    "youtube-live-stream-views-6h",
    "youtube-boosting",
    "9.44",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21381,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (7 Day)",
    "youtube-live-stream-views-7-day",
    "youtube-boosting",
    "262.43",
    50,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19711,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (720 Min)",
    "youtube-live-stream-views-720-min",
    "youtube-boosting",
    "19.09",
    50,
    5000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19706,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (90 Min)",
    "youtube-live-stream-views-90-min",
    "youtube-boosting",
    "2.39",
    50,
    5000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19695,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (Organic, Lifetime)",
    "youtube-live-stream-views-real-accounts-lifetime",
    "youtube-boosting",
    "4.75",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19693,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (Organic, 30-Day Guarantee)",
    "youtube-live-stream-views-real-accounts-refill-30d",
    "youtube-boosting",
    "4.15",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19694,
    "youtube",
    "youtube",
    "YouTube Live Stream Views (Organic, 365-Day Guarantee)",
    "youtube-live-stream-views-real-accounts-refill-365d",
    "youtube-boosting",
    "4.39",
    10,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21256,
    "youtube",
    "youtube",
    "YouTube Post Likes",
    "youtube-post-likes-no-refill",
    "youtube-boosting",
    "0.38",
    10,
    1000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19735,
    "youtube",
    "youtube",
    "YouTube Shares",
    "youtube-shares",
    "youtube-boosting",
    "10.24",
    1000,
    100000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19575,
    "youtube",
    "youtube",
    "YouTube Subscribers (Lifetime)",
    "youtube-subscribers-lifetime",
    "youtube-boosting",
    "251.51",
    100,
    100000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19606,
    "youtube",
    "youtube",
    "YouTube Subscribers",
    "youtube-subscribers-no-refill",
    "youtube-boosting",
    "1.05",
    10,
    1000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19573,
    "youtube",
    "youtube",
    "YouTube Subscribers (30-Day Guarantee)",
    "youtube-subscribers-refill-30d",
    "youtube-boosting",
    "203.60",
    100,
    50000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19570,
    "youtube",
    "youtube",
    "YouTube Subscribers (Premium, 30-Day Guarantee)",
    "youtube-subscribers-high-quality-refill-30d",
    "youtube-boosting",
    "130.49",
    50,
    100000,
    "15 hours 57 minutes",
    "/logos/youtube.svg",
  ],
  [
    19571,
    "youtube",
    "youtube",
    "YouTube Subscribers (Premium, 90-Day Guarantee)",
    "youtube-subscribers-high-quality-refill-90d",
    "youtube-boosting",
    "262.02",
    100,
    100000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19586,
    "youtube",
    "youtube",
    "YouTube Views (RAV Monetization PH)",
    "youtube-views",
    "youtube-boosting",
    "40.12",
    500,
    100000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    21254,
    "youtube",
    "youtube",
    "YouTube Views (Lifetime)",
    "youtube-views-lifetime",
    "youtube-boosting",
    "2.14",
    100,
    200000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    20610,
    "youtube",
    "youtube",
    "YouTube Views",
    "youtube-views-no-refill",
    "youtube-boosting",
    "6.98",
    100,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    20611,
    "youtube",
    "youtube",
    "YouTube Views (30-Day Guarantee)",
    "youtube-views-refill-30d",
    "youtube-boosting",
    "7.79",
    100,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    20612,
    "youtube",
    "youtube",
    "YouTube Views (365-Day Guarantee)",
    "youtube-views-refill-365d",
    "youtube-boosting",
    "8.49",
    100,
    10000000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19583,
    "youtube",
    "youtube",
    "YouTube Views (90-Day Guarantee)",
    "youtube-views-refill-90d",
    "youtube-boosting",
    "35.93",
    500,
    500000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    19578,
    "youtube",
    "youtube",
    "YouTube Watch Time (Instant, Organic, 30-Day Guarantee)",
    "youtube-watch-time-instant-real-refill-30d",
    "youtube-boosting",
    "251.51",
    50,
    4000,
    "New Service",
    "/logos/youtube.svg",
  ],
  [
    30001,
    "spotify",
    "spotify",
    "Spotify Plays",
    "spotify-plays-no-refill",
    "spotify-boosting",
    "0.31",
    100,
    1000000,
    "1 hours",
    "/logos/spotify.png",
  ],
  [
    30002,
    "spotify",
    "spotify",
    "Spotify Plays (Lifetime)",
    "spotify-plays-lifetime",
    "spotify-boosting",
    "0.43",
    100,
    1000000,
    "1 hours",
    "/logos/spotify.png",
  ],
  [
    30003,
    "spotify",
    "spotify",
    "Spotify Plays (30-Day Guarantee)",
    "spotify-plays-refill-30d",
    "spotify-boosting",
    "0.38",
    100,
    1000000,
    "1 hours",
    "/logos/spotify.png",
  ],
] as const satisfies readonly BoostingCatalogRow[];
